name: README.md
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.me_TOKEN }}
          GIST_ID: ${{ secrets.Antrhing }}
          TIMEZONE: Asia/Seoul
